import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { getEnvironmentData } from 'worker_threads'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [news, setNews] = useState([{}])
  
  useEffect(() =>{
    //Call the URL of the server where is the server running to fetch data
    
    async function getData(){
      const response = await fetch("http://localhost:4000/getNews");
      const data = await response.json();  
      setNews(data);
    }
    getData();
  },[])
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">API REST with NEXT, NODE and EXPRESS!</a>
        </h1>
        
        {
          news != undefined && news.map(new1 => {
            return(
              <fieldset className={styles.fieldset}>
              <h2 key={new1.title}> {new1.title} ({new1.country[0]}) </h2>
              <h3 key={new1.keywords}> {new1.keywords != null ? new1.keywords[0] : ""} </h3>
              <p key={`${new1.title}${new1.link}`}> {new1.description} 
              <Link href="example.com" as={new1.link} key={new1.link}> 
                <a target="_blank" key={`${new1.link}mas`}>... más </a> 
              </Link>
              </p>
              </fieldset>
            )
          })
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Juan Carlos Cabello
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
